Upgrades project to Gradle 6.8.3
wooga/atlas-slack pull request #8
Opened 2021-04-13 10:48 UTC by Azurelol

2021-04-14 15:50 UTC, Larusso requested changes
the copyright header are still missing and I think some imports can be optimized

2021-04-15 09:04 UTC, Larusso approved these changes

2021-04-15 09:05 UTC, Larusso commented
Can you also update the PR description please? Then we can merge this.

2021-04-15 09:20 UTC, Azurelol commented
> 
> 
> Can you also update the PR description please? Then we can merge this.

Done

2021-04-15 15:20 UTC, merged